services:
  db:
    image: mariadb:12.1
    environment:
      MARIADB_DATABASE: app
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
  php:
    build:
      context: ./back
      dockerfile: ./deploy/docker/php/Dockerfile
      target: dev
    volumes:
      - ./back:/app
    command: sh -c "deploy/docker/php/dev_entrypoint.sh && php-fpm"
    depends_on:
      - db
  nginx:
    build:
      context: ./back/deploy/docker/nginx
    ports:
      - "8802:80"
    volumes:
      - ./back/public:/app/public
    depends_on:
      - php
  adminer:
    image: adminer:latest
    ports:
      - "8803:8080"
    depends_on:
      - db
  react:
    image: node:25
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "8801:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
volumes:
  dbdata:
