services:
  db:
    image: mariadb:12.1
    environment:
      MARIADB_DATABASE: app
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
  php:
    build:
      context: ./back
      dockerfile: ./deploy/docker/php/Dockerfile
      target: dev
    volumes:
      - ./back:/app
    depends_on:
      - db
  nginx:
    build:
      context: ./back/deploy/docker/nginx
    ports:
      - "8802:80"
    volumes:
      - ./back/public:/app/public
    depends_on:
      - php
  adminer:
    image: adminer:latest
    ports:
      - "8803:8080"
    depends_on:
      - db
volumes:
  dbdata:
